---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-qfns-categraf-operator-v1-categrafmonitor
  failurePolicy: Fail
  name: mcategrafmonitor.kb.io
  rules:
  - apiGroups:
    - qfns.categraf-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - categrafmonitors
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-qfns-categraf-operator-v1-categrafmonitor
  failurePolicy: Fail
  name: vcategrafmonitor.kb.io
  rules:
  - apiGroups:
    - qfns.categraf-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - categrafmonitors
  sideEffects: None
