# permissions for end users to edit categrafglobals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: categrafglobal-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: categraf-operator
    app.kubernetes.io/part-of: categraf-operator
    app.kubernetes.io/managed-by: kustomize
  name: categrafglobal-editor-role
rules:
- apiGroups:
  - qfns.categraf-operator
  resources:
  - categrafglobals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qfns.categraf-operator
  resources:
  - categrafglobals/status
  verbs:
  - get
