---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - qfns.categraf-operator
  resources:
  - categrafglobals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qfns.categraf-operator
  resources:
  - categrafglobals/finalizers
  verbs:
  - update
- apiGroups:
  - qfns.categraf-operator
  resources:
  - categrafglobals/status
  verbs:
  - get
  - patch
  - update
