apiVersion: qfns.categraf-operator/v1
kind: CategrafMonitor
metadata:
  labels:
    app.kubernetes.io/name: categraf-operator
    app.kubernetes.io/managed-by: kustomize
  name: categrafmonitor-sample
spec:
  # TODO(user): Add fields here
