apiVersion: qfns.categraf-operator/v1
kind: Categrafglobal
metadata:
  labels:
    app.kubernetes.io/name: categraf-operator
    app.kubernetes.io/managed-by: kustomize
  name: categrafglobal-sample
spec:
  global:
    print_configs: false
    hostname: ''
    omit_hostname: false
    interval: 15
    providers:
      - local
    concurrency: -1
  log:
    file_name: stdout
    max_size: 10001
    max_age: 1
    max_backups: 1
    local_time: true
    compress: false
  writer_opt:
    batch: 1000
    chan_size: 1000000
  writers:
    - url: http://127.0.0.1:17000/prometheus/v1/write
      basic_auth_user: ''
      basic_auth_pass: ''
      timeout: 5000
      dial_timeout: 2500
      max_idle_conns_per_host: 100
  http:
    enable: false
    address: ':9100'
    print_access: false
    run_mode: release
    ignore_hostname: false
    ignore_global_labels: false
  ibex:
    enable: false
    interval: 1000ms
    servers:
      - 127.0.0.1:20090
    meta_dir: ./meta
  heartbeat:
    enable: true
    url: http://127.0.0.1:17000/v1/n9e/heartbeat
    interval: 10
    basic_auth_user: ''
    basic_auth_pass: ''
    timeout: 5000
    dial_timeout: 2500
    max_idle_conns_per_host: 100
  prometheus:
    enable: false
    scrape_config_file: /path/to/in_cluster_scrape.yaml
    log_level: info
